#1.-NÚMERO TOTAL DE CONSULTAS
SELECT * FROM consulta;

#2.-NÚMERO TOTAL DE HOSPITALIZACIÓN
SELECT * FROM hospitalizacion;

#3.-NÚMERO TOTAL DE MASCOTAS
SELECT * FROM mascota;

#4.-NÚMERO TOTAL DE EMPLEADOS
SELECT * FROM empleados;

#5.-NÚMERO DE HOSPITALIZACIONES CON RESTRICCIÓN
SELECT * FROM hospitalizacion WHERE costo_hosp < 1000;

#6.-NÚMERO DE CONSULTAS CON RESTRICCIÓN 
SELECT * FROM consulta WHERE costo_consulta > 200;

#7.-INCINERACIONES CON RESTRICCIÓN
SELECT * FROM Incineracion WHERE costo_ins >200;

#8.-NÚMERO DE MEDICAMENTOS CON RESTRICCIÓN
SELECT * FROM medicamento WHERE precio_med > 200;