#1.-CREACIÓN DE LA TABLA
CREATE TABLE Puesto(
Puesto_id NUMERIC(2,0) NOT NULL,
Nivel CHAR (1) NOT NULL,
Clave VARCHAR(3) NOT NULL,
Sueldo NUMERIC (8,2) NOT NULL,
#2.-CREACIÓN DE LA PRIMARY KEY
CONSTRAINT Puesto_pk PRIMARY KEY (Puesto_id),
#3.-NIVEL DE PUESTO SUJETO A LOS VALORES PEDIDOS
CONSTRAINT cp_Nivel_chk CHECK (Nivel IN ('a', 'b', 'c')),
#5.-SUELDO SUJETO AL VALOR PEDIDO
CONSTRAINT cp_Sueldo_chk CHECK (Sueldo =< 10000),
#4.-CLAVE ÚNICA
CONSTRAINT cp_Clave_uk UNIQUE (Clave),
);
